# Use an official Node.js image (LTS)
FROM node:20

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Build the TypeScript app
RUN npm run build

# Expose NestJS default port
EXPOSE 3000

# Start the application
CMD ["node", "dist/main"]
